export const NAV = [
  { href: "/", label: "Home" },
  { href: "/about-us/", label: "About Us" },
  { href: "/digital-services/", label: "Digital Services" },
  { href: "/our-work/", label: "Our Work" },
  { href: "/packages/", label: "Packages" },
  { href: "/blogs/", label: "Blogs" },
  { href: "/get-in-touch/", label: "Get In Touch" },
];

export const CLIENT_LOGOS = [
  { src: "/logos/AGB.png", alt: "AGB Construction" },
  { src: "/logos/AOO White.png", alt: "Aspects of Oak" },
  { src: "/logos/AP.png", alt: "Auric Performance" },
  { src: "/logos/BFB.png", alt: "BFB" },
  { src: "/logos/BRS.png", alt: "BRS" },
  { src: "/logos/EP.png", alt: "Evolution Padel" },
  { src: "/logos/GJ Wheels White.png", alt: "GJ Wheels" },
  { src: "/logos/Lost in Hound 2.png", alt: "Lost in Hound" },
  { src: "/logos/MTD White.png", alt: "MTD" },
  { src: "/logos/NR White.png", alt: "New Reflexions" },
  { src: "/logos/Oriels White.png", alt: "Oriels" },
  { src: "/logos/Palace.png", alt: "Palace Nightclub" },
  { src: "/logos/RNP White.png", alt: "RNP" },
  { src: "/logos/SDR White.png", alt: "SDR" },
  { src: "/logos/SMS.png", alt: "Search Mortgage Solutions" },
  { src: "/logos/The Loft.png", alt: "The Loft" },
  { src: "/logos/Vaala White.png", alt: "Vaala" },
  { src: "/logos/Waldrons White 2.png", alt: "Waldron's Patisserie" },
  { src: "/logos/Yvonne 3.png", alt: "Yvonne Coomber" },
];

export const PARTNER_LOGOS = [
  { src: "/brands/Canva.png", alt: "Canva" },
  { src: "/brands/Adobe.png", alt: "Adobe" },
  { src: "/brands/Chat GPT.png", alt: "ChatGPT" },
  { src: "/brands/Claude.png", alt: "Claude" },
  { src: "/brands/Expo.png", alt: "Expo" },
  { src: "/brands/Google.png", alt: "Google" },
  { src: "/brands/Github.png", alt: "GitHub" },
  { src: "/brands/Java.png", alt: "Java" },
  { src: "/brands/Linkedin.png", alt: "LinkedIn" },
  { src: "/brands/Semrush.png", alt: "Semrush" },
  { src: "/brands/React.png", alt: "React" },
  { src: "/brands/Stripe.png", alt: "Stripe" },
  { src: "/brands/Supabase.png", alt: "Supabase" },
  { src: "/brands/VS Code.png", alt: "VS Code" },
  { src: "/brands/Vercel.png", alt: "Vercel" },
  { src: "/brands/Yoast.png", alt: "Yoast" },
];

export const SERVICES = [
  {
    title: "Digital Strategy",
    href: "/digital-services/",
    icon: "/icons/SEO.png",
    text: "Great marketing starts with a clear plan. We build focused digital strategies that align your website, social media, paid campaigns and content into one joined-up approach.",
  },
  {
    title: "Web Development",
    href: "/digital-services/",
    icon: "/icons/UI UX.png",
    text: "We design and build fast, modern, fully responsive websites that are created to convert visitors into customers.",
  },
  {
    title: "Social Media Management",
    href: "/digital-services/",
    icon: "/icons/Brand.png",
    text: "We manage your social media presence across every platform, ensuring consistent posting, active community management and genuine audience growth.",
  },
  {
    title: "Paid Media",
    href: "/digital-services/",
    icon: "/icons/Reporting.png",
    text: "We create and manage paid advertising campaigns across Google, Meta and LinkedIn that generate real leads and sales.",
  },
  {
    title: "SEO & CRO",
    href: "/digital-services/",
    icon: "/icons/SEO.png",
    text: "We optimise your website to increase visibility in search engines and improve conversion performance.",
  },
  {
    title: "Email Marketing",
    href: "/digital-services/",
    icon: "/icons/AI.png",
    text: "We build and manage email marketing strategies that keep your audience engaged, nurture leads and drive repeat business.",
  },
  {
    title: "LinkedIn Outreach & Lead Generation",
    href: "/digital-services/",
    icon: "/icons/Linkedin.png",
    text: "We run targeted LinkedIn outreach campaigns that put your business directly in front of the right decision makers.",
  },
  {
    title: "AI & Marketing Automation",
    href: "/digital-services/",
    icon: "/icons/AI.png",
    text: "We implement AI-powered tools and automation workflows that improve efficiency, reduce workload and scale what works.",
  },
  {
    title: "App Design & App Store Optimisation",
    href: "/digital-services/",
    icon: "/icons/App.png",
    text: "We design, build and launch mobile applications for iOS and Android, from initial concept through to App Store submission.",
  },
  {
    title: "UX & UI Design",
    href: "/digital-services/",
    icon: "/icons/UI UX.png",
    text: "We design intuitive, visually compelling user experiences that make your website and digital platforms easy and enjoyable to use.",
  },
  {
    title: "Analytics & Reporting",
    href: "/digital-services/",
    icon: "/icons/Reporting.png",
    text: "We provide clear, honest reporting and real-time insights so you always know exactly how your marketing is performing.",
  },
  {
    title: "Graphic Design",
    href: "/digital-services/",
    icon: "/icons/Brand.png",
    text: "From social media graphics and ad creative to brochures, presentations and brand assets, we create clean, impactful designs.",
  },
  {
    title: "Branding & Brand Identity",
    href: "/digital-services/",
    icon: "/icons/Brand.png",
    text: "We build distinctive brand identities that position your business professionally and memorably.",
  },
];

export const TESTIMONIALS = [
  { quote: "MM Digital have been fantastic to work with, proactive, creative and highly supportive. The content they produce for our social media is outstanding and has truly elevated our online presence.", name: "Robert", role: "CEO" },
  { quote: "Just the partner we need to level up our Social Media presence and Brand Identity across the board. Really crucial to have fluid communication throughout.", name: "David", role: "Director" },
  { quote: "We couldn’t be happier to have utilised MM Digital’s services to level up our presence across the board. We look forward to continuing our partnership.", name: "George", role: "Director" },
  { quote: "MM Digital has supported us in navigating through complex strategic approaches to target audiences across the European market. This has helped deliver ROI quickly for us.", name: "Jeremy", role: "CEO" },
  { quote: "We have now worked with MM Digital for years. It’s been brilliant to see concise planning, great communication and constant support.", name: "Yvonne", role: "Founder" },
  { quote: "Superb service throughout the onboarding procedure. The communication is second to none. Very impressed with the results.", name: "Dr. Varun Shethi", role: "Founder" },
  { quote: "MM Digital ran our social media presence on our behalf. What worked really well for the business was the flexibility and communication shown by MM Digital.", name: "Keyvan", role: "Founder/CEO" },
  { quote: "MM Digital is a top-notch marketing company. Their marketing strategies and creative solutions have consistently exceeded our expectations.", name: "Joel", role: "Senior Executive" },
  { quote: "Working with MM Digital has completely transformed our online presence across social media & website. From strategy through to delivery, their team took the time to understand our business.", name: "Stuart", role: "Founder & Director" },
  { quote: "Working with MM Digital has been seamless from the start. They understood our vision immediately and helped us turn it into a clear, consistent digital strategy.", name: "Richard", role: "Founder & Director" },
  { quote: "From day one, the team understood exactly how to position our business, helping us connect with the right audience and build genuine traction.", name: "Tyrone", role: "Managing Director" },
  { quote: "Partnering with MM Digital has been a game-changer for our brand. MM Digital consistently delivers results with professionalism and passion.", name: "William", role: "Managing Director" },
  { quote: "Max and the team have provided us with the support we needed to launch the marketing for our new venture and get ourselves noticed.", name: "Scott", role: "CEO & Co-Founder" },
];

export const BLOGS = [
  {
    slug: "why-your-business-needs-to-be-found-on-ai-search-not-just-google",
    title: "Why Your Business Needs to Be Found on AI Search (Not Just Google)",
    date: "September 1, 2026",
    author: "MM Digital",
    image: "/icons/AI.png",
    excerpt: "Google is no longer the only place your customers are searching. Discover what GEO means and how to make your business visible in AI-generated answers.",
  },
  {
    slug: "what-makes-a-high-converting-website-in-2026",
    title: "What Makes a High Converting Website in 2026",
    date: "August 2, 2026",
    author: "MM Digital",
    image: "/icons/UI UX.png",
    excerpt: "Having a website is no longer enough. Here’s what separates the sites that turn visitors into customers from the ones that just look the part.",
  },
  {
    slug: "why-summer-2026-is-the-most-important-season-for-your-digital-marketing",
    title: "Why Summer 2026 Is the Most Important Season for Your Digital Marketing",
    date: "July 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/Brand.png",
    excerpt: "Summer is one of the biggest opportunities in the marketing calendar. If your brand is not showing up consistently, you could be missing valuable attention.",
  },
  {
    slug: "why-every-business-needs-a-digital-strategy",
    title: "Why Every Business Needs a Digital Strategy",
    date: "June 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/SEO.png",
    excerpt: "Posting on social media is not a strategy. Running ads is not a strategy. A digital strategy is what makes everything else actually work.",
  },
  {
    slug: "how-to-generate-leads-without-a-big-budget",
    title: "How to Generate Leads Without a Big Budget",
    date: "May 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/Reporting.png",
    excerpt: "You do not need to spend a fortune to grow your pipeline. You need a smarter strategy.",
  },
  {
    slug: "6135-2",
    title: "Why Most Businesses Are Wasting Their Ad Spend",
    date: "April 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/Reporting.png",
    excerpt: "Businesses across the UK are spending thousands on paid advertising every month and seeing very little in return.",
  },
  {
    slug: "marketing-in-2026",
    title: "Marketing in 2026: What Growing Businesses Must Get Right",
    date: "March 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/Brand.png",
    excerpt: "March marks the point in the year where initial plans either start gaining traction, or quietly lose momentum.",
  },
  {
    slug: "ai-in-business-2026",
    title: "AI in 2026: The Businesses That Win Will Be the Ones That Use It Properly",
    date: "February 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/AI.png",
    excerpt: "Artificial Intelligence is no longer a trend. It is no longer experimental. And it is certainly no longer optional.",
  },
  {
    slug: "smarter-marketing-2026",
    title: "January 2026: A Smarter Year for Marketing",
    date: "January 2, 2026",
    author: "Maximilian Madl",
    image: "/icons/SEO.png",
    excerpt: "A new year doesn’t demand louder marketing. It demands smarter marketing.",
  },
];

export const CASE_STUDIES = [
  { slug: "oriels-case-study", title: "Oriels Exeter", summary: "Launching Oriels Exeter into one of the city’s most in-demand venues." },
  { slug: "aspects-of-oaks-case-study", title: "Aspects of Oak", summary: "Premium carpentry and construction with a stronger digital presence." },
  { slug: "yvonne-coombers-case-study", title: "Yvonne Coomber", summary: "Brand, social and digital growth for a distinctive art business." },
  { slug: "waldrons-patisseries-case-study", title: "Waldron's Patisserie", summary: "Content, social and visibility that matches the quality of the product." },
  { slug: "ashmore-building-companys-case-study", title: "Ashmore Building Company", summary: "Lead generation and digital positioning for a construction brand." },
  { slug: "the-100-day-plan-companys-case-study", title: "The 100 Day Plan Company", summary: "A structured digital approach for a professional services brand." },
];
